[workspace]
resolver = "2"
members = [
	"grpc",
	"node",
	"sampler",
	"data_fetcher",
	"common",
]

[patch.crates-io]
eth2_ssz = { path = "version-meld/eth2_ssz" }
enr = { path = "version-meld/enr" }
discv5 = { path = "version-meld/discv5" }